-- it_* 테이블: Next.js 서버(Service Role) API 전용
-- RLS만 켜고 정책이 없으면 PostgREST INSERT/SELECT/UPDATE/DELETE가 차단됩니다.

ALTER TABLE it_projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_task_dependencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_tech_capabilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_project_issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE it_reviews DISABLE ROW LEVEL SECURITY;

NOTIFY pgrst, 'reload schema';
